# Generated by Django 5.1.4 on 2025-08-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TryoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('banner', models.ImageField(upload_to='tryouts/')),
            ],
        ),
        migrations.CreateModel(
            name='TryoutRegistrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('weight_class', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('tryout_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='tryouts.tryoutevent')),
            ],
        ),
    ]
