# Generated by Django 5.1.4 on 2025-08-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryoutregistrant',
            name='image',
            field=models.ImageField(default='fighters/SILHOUETTE.jpg', upload_to='tryoutRegistrant/'),
        ),
    ]
